# Generated by Django 2.1.7 on 2026-02-06 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crimereporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AwarenessPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
